# Generated by Django 5.1.1 on 2025-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField(help_text="e.g., '40% increase in sales'")),
                ('image', models.ImageField(upload_to='casestudies/')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
