# Generated by Django 5.2.5 on 2026-04-05 20:02

import casestudies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-published_date'], 'verbose_name': 'Case Study', 'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='image',
            field=models.ImageField(help_text='Upload an image (JPG, PNG, or WebP, max 5MB)', upload_to='casestudies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), casestudies.models.validate_image_size]),
        ),
    ]
