# Generated by Django 5.1.1 on 2025-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
