# Generated by Django 5.2.5 on 2026-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('current_website', models.URLField(blank=True)),
                ('branding_notes', models.TextField(blank=True)),
                ('colour_preferences', models.TextField(blank=True)),
                ('layout_pages', models.TextField(blank=True)),
                ('font_preferences', models.TextField(blank=True)),
                ('image_notes', models.TextField(blank=True)),
                ('additional_features', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
